#!/usr/bin/env bash
# Corpus health check. Exits non-zero on failure so it can gate a commit.
#
#   bash corpus/lint.sh            check
#   bash corpus/lint.sh --index    regenerate index.md's catalog block, then check
#
# Checks: every wiki page has summary: + updated: frontmatter; every relative
# link resolves; no page exceeds MAX_LINES body lines; no page references a
# top-level directory the repo has abandoned.

set -uo pipefail

CORPUS="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(dirname "$CORPUS")"
MAX_LINES=200
FAIL=0

say()  { printf '%s\n' "$*"; }
bad()  { printf '  ✗ %s\n' "$*"; FAIL=1; }

# --- frontmatter helpers -----------------------------------------------------
# Print the value of a frontmatter key, or nothing when absent/not a block.
fm() { # fm <file> <key>
  awk -v key="$2" '
    NR==1 { if ($0 != "---") exit; next }
    /^---[[:space:]]*$/ { exit }
    index($0, key ": ") == 1 { print substr($0, length(key) + 3); exit }
  ' "$1"
}

# Body line count (frontmatter excluded).
body_lines() {
  awk '
    NR==1 && $0=="---" { infm=1; next }
    infm && /^---[[:space:]]*$/ { infm=0; next }
    !infm { n++ }
    END { print n+0 }
  ' "$1"
}

# --- 1. wiki frontmatter -----------------------------------------------------
say "Frontmatter"
shopt -s nullglob
WIKI_PAGES=("$CORPUS"/wiki/*.md)
if [ ${#WIKI_PAGES[@]} -eq 0 ]; then
  bad "corpus/wiki/ has no pages"
fi
for f in "${WIKI_PAGES[@]}"; do
  rel="${f#"$ROOT"/}"
  [ -n "$(fm "$f" summary)" ] || bad "$rel: missing 'summary:' frontmatter"
  u="$(fm "$f" updated)"
  if [ -z "$u" ]; then
    bad "$rel: missing 'updated:' frontmatter"
  elif ! printf '%s' "$u" | grep -Eq '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'; then
    bad "$rel: 'updated: $u' is not an absolute YYYY-MM-DD date"
  fi
done

# --- 2. page size ------------------------------------------------------------
say "Page size (max $MAX_LINES body lines)"
for f in "${WIKI_PAGES[@]}"; do
  n="$(body_lines "$f")"
  [ "$n" -le "$MAX_LINES" ] || bad "${f#"$ROOT"/}: $n body lines — split it"
done

# --- 3. relative links resolve ----------------------------------------------
say "Relative links"
ALL_MD=("$CORPUS"/*.md "$CORPUS"/wiki/*.md "$CORPUS"/todos/*.md \
        "$CORPUS"/briefs/todo/*.md "$CORPUS"/briefs/done/*.md \
        "$CORPUS"/briefs/superseded/*.md)
for f in "${ALL_MD[@]}"; do
  [ -f "$f" ] || continue
  dir="$(dirname "$f")"
  # Markdown inline links only; skip http(s), mailto and pure anchors.
  while read -r target; do
    case "$target" in http://*|https://*|mailto:*|'#'*|'') continue ;; esac
    path="${target%%#*}"
    [ -n "$path" ] || continue
    [ -e "$dir/$path" ] || bad "${f#"$ROOT"/}: dead link -> $target"
  done < <(grep -oE '\]\([^)]+\)' "$f" | sed -E 's/^\]\(//; s/\)$//')
done

# --- 4. abandoned path roots -------------------------------------------------
# A page that describes a top-level directory the repo no longer has is stale.
# Link targets are already covered by check 3; this catches *prose* claims.
# A mention is allowed when the line marks it as history ("moved out", "removed",
# "used to", "no longer") — the wiki is allowed to record what left.
say "Abandoned paths"
ABANDONED=(showcase infrastructure)
HISTORY_RE='move out|moved|removed|no longer|used to|left the repo|was in|deleted|pruned'
for stale in "${ABANDONED[@]}"; do
  [ -d "$ROOT/$stale" ] && continue
  while IFS=: read -r file line text; do
    [ -n "${file:-}" ] || continue
    printf '%s' "$text" | grep -Eqi "$HISTORY_RE" && continue
    bad "${file#"$ROOT"/}:$line references '$stale/', which no longer exists"
  done < <(grep -rn --include='*.md' -E "(^|[^A-Za-z0-9_/.-])$stale/" "$CORPUS" 2>/dev/null \
           | grep -v "^$CORPUS/log.md:" || true)
done

# --- 5. index catalog --------------------------------------------------------
regen_index() {
  local tmp; tmp="$(mktemp)"
  {
    echo '<!-- CATALOG:START — generated by lint.sh --index; do not hand-edit -->'
    for f in "$CORPUS"/wiki/*.md; do
      [ -f "$f" ] || continue
      printf -- '- [%s](wiki/%s) — %s\n' \
        "$(basename "$f" .md)" "$(basename "$f")" "$(fm "$f" summary)"
    done
    echo '<!-- CATALOG:END -->'
  } > "$tmp"
  awk -v cat="$tmp" '
    /^<!-- CATALOG:START/ { while ((getline line < cat) > 0) print line; skip=1; next }
    /^<!-- CATALOG:END/   { skip=0; next }
    !skip
  ' "$CORPUS/index.md" > "$CORPUS/index.md.new" && mv "$CORPUS/index.md.new" "$CORPUS/index.md"
  rm -f "$tmp"
  say "Regenerated corpus/index.md catalog."
}

if [ "${1:-}" = "--index" ]; then
  regen_index
fi

say "Index catalog"
for f in "${WIKI_PAGES[@]}"; do
  grep -q "wiki/$(basename "$f")" "$CORPUS/index.md" \
    || bad "${f#"$ROOT"/}: orphan — not in index.md (run: bash corpus/lint.sh --index)"
done

# --- verdict -----------------------------------------------------------------
if [ "$FAIL" -eq 0 ]; then
  say "OK — corpus is clean."
else
  say "FAILED — fix the findings above."
fi
exit "$FAIL"
