// Generates the Open Graph card — the one image this site ships.
//
// It is the same drawing as the pages: the marquee in true isometric, with a
// dimension line and the sheet's title block. Nothing here is a photograph,
// because the site does not use photography.
//
// Social platforms refuse an SVG og:image, so the drawing is wrapped in
// scripts/og-card.html with the real self-hosted IBM Plex faces (a rasterizer's
// fallback font would also guess at ș and ț), screenshotted by headless Chrome
// at 1200x630, and palette-encoded to public/images/og-image.png, well under
// the 300 KB WhatsApp accepts.
//
//   npm run subcort:og            (CHROME=/path/to/chrome to pick the binary)

import { execFileSync } from "node:child_process";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import sharp from "sharp";
import {
  marquee, isometric, pts, tone, dimension,
  INK, LINE, SIGNAL, SHEET,
} from "../src/lib/draft.ts";

const scriptsDir = dirname(fileURLToPath(import.meta.url));
const outDir = join(scriptsDir, "..", "public", "images");

const W = 1200, H = 630;
const M = marquee();
const P = isometric({ scale: 13.5, cx: 880, cy: 300 });

let g = "";
const deck = M.panels.find((p) => p.part === "deck");
g += `<polygon points="${pts(deck.quad, P)}" fill="#EDEFF1" stroke="${LINE}" stroke-width="1.1"/>`;
for (const [a, b] of M.members) {
  const [x1, y1] = P(a); const [x2, y2] = P(b);
  g += `<line x1="${x1.toFixed(1)}" y1="${y1.toFixed(1)}" x2="${x2.toFixed(1)}" y2="${y2.toFixed(1)}" stroke="${INK}" stroke-width="1.5" stroke-linecap="round"/>`;
}
for (const p of M.panels.filter((p) => p.part !== "deck")) {
  g += `<polygon points="${pts(p.quad, P)}" fill="${tone(p.quad)}" fill-opacity="0.92" stroke="${LINE}" stroke-width="1" stroke-linejoin="round"/>`;
}
// the ridge, in the annotation colour
const r0 = P([0, M.spec.ridge, -M.hd]);
const r1 = P([0, M.spec.ridge, M.hd]);
g += `<line x1="${r0[0].toFixed(1)}" y1="${r0[1].toFixed(1)}" x2="${r1[0].toFixed(1)}" y2="${r1[1].toFixed(1)}" stroke="${SIGNAL}" stroke-width="1.8"/>`;
// the span, dimensioned
const d0 = P([-M.hw, 0, M.hd]);
const d1 = P([M.hw, 0, M.hd]);
g += dimension([d0[0], d0[1]], [d1[0], d1[1]], "15,0 m", { offset: -46 });

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}">
  <rect width="${W}" height="${H}" fill="${SHEET}"/>
  <g font-family="'IBM Plex Mono',monospace" font-size="17" font-weight="500" fill="${SIGNAL}" letter-spacing="1.6">
    <text x="74" y="96">SUBCORT · GORJ — OLTENIA</text>
  </g>
  <line x1="74" y1="120" x2="${W - 74}" y2="120" stroke="${INK}" stroke-width="1.5"/>
  ${g}
  <g font-family="'IBM Plex Sans',system-ui,sans-serif" fill="${INK}">
    <text x="74" y="228" font-size="60" font-weight="600" letter-spacing="-2">Un spațiu pregătit,</text>
    <text x="74" y="296" font-size="60" font-weight="600" letter-spacing="-2">oriunde ai nevoie de el.</text>
    <text x="74" y="360" font-size="23" font-weight="400" fill="#5E7180">Corturi pentru evenimente, montate la tine acasă.</text>
  </g>
  <line x1="74" y1="470" x2="${W - 74}" y2="470" stroke="${INK}" stroke-width="1.5"/>
  <g font-family="'IBM Plex Mono',monospace" font-size="14" font-weight="500" fill="#5E7180" letter-spacing="1.2">
    <text x="74" y="500">DESCHIDERE</text><text x="74" y="530" font-size="21" fill="${INK}">8 – 20 m</text>
    <text x="330" y="500">SUPRAFAȚĂ</text><text x="330" y="530" font-size="21" fill="${INK}">64 – 300 m²</text>
    <text x="610" y="500">CAPACITATE</text><text x="610" y="530" font-size="21" fill="${INK}">40 – 320</text>
    <text x="880" y="500">MONTAJ</text><text x="880" y="530" font-size="21" fill="${INK}">La tine acasă</text>
  </g>
</svg>
`;

// Fonts resolve from the repo-root node_modules; latin-ext carries ă â î ș ț.
const FONTS = "../../../node_modules/@fontsource";
const LATIN_EXT =
  "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329," +
  "U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF";
const face = (family, file, weight, format, ext) =>
  `@font-face{font-family:"${family}";src:url("${file}") format("${format}");font-weight:${weight};${ext ? `unicode-range:${LATIN_EXT};` : ""}}`;

const html = `<!doctype html><html lang="ro"><head><meta charset="utf-8">
<!--
  GENERATED by scripts/gen-og.mjs — edit the generator, not this file.
  SOURCE for public/images/og-image.png. To regenerate: npm run subcort:og
-->
<style>
${face("IBM Plex Sans", `${FONTS}-variable/ibm-plex-sans/files/ibm-plex-sans-latin-ext-wght-normal.woff2`, "100 700", "woff2-variations", true)}
${face("IBM Plex Sans", `${FONTS}-variable/ibm-plex-sans/files/ibm-plex-sans-latin-wght-normal.woff2`, "100 700", "woff2-variations", false)}
${face("IBM Plex Mono", `${FONTS}/ibm-plex-mono/files/ibm-plex-mono-latin-ext-500-normal.woff2`, 500, "woff2", true)}
${face("IBM Plex Mono", `${FONTS}/ibm-plex-mono/files/ibm-plex-mono-latin-500-normal.woff2`, 500, "woff2", false)}
*{margin:0;padding:0}
html,body{width:${W}px;height:${H}px;overflow:hidden}
svg{display:block}
</style></head><body>
${svg}</body></html>
`;

const cardPath = join(scriptsDir, "og-card.html");
await writeFile(cardPath, html);
console.log("wrote scripts/og-card.html");

const tmp = await mkdtemp(join(tmpdir(), "subcort-og-"));
try {
  const shot = join(tmp, "card.png");
  execFileSync(process.env.CHROME ?? "google-chrome", [
    "--headless=new", "--disable-gpu", "--hide-scrollbars",
    "--force-device-scale-factor=1", `--window-size=${W},${H}`,
    // give the @font-face files time to load before the capture
    "--virtual-time-budget=3000",
    `--screenshot=${shot}`, pathToFileURL(cardPath).href,
  ], { stdio: "ignore" });
  const info = await sharp(shot)
    .png({ palette: true, compressionLevel: 9 })
    .toFile(join(outDir, "og-image.png"));
  if (info.width !== W || info.height !== H) {
    throw new Error(`og-image.png came out ${info.width}x${info.height}, expected ${W}x${H}`);
  }
  console.log(`wrote public/images/og-image.png (${Math.round(info.size / 1024)} KB)`);
} finally {
  await rm(tmp, { recursive: true, force: true });
}
